package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.DeviceOrientation;
import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.model.CartItem;
import com.kiloux.restopos.service.CartService;
import com.kiloux.restopos.ui.RetroButton;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;

public class CartPanel extends JPanel {

    // Variables declaration - do not modify
    private javax.swing.JLabel titleLabel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable cartTable;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel funcPanel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JPanel buttonPanel;
    private com.kiloux.restopos.ui.RetroButton btnBack;
    private com.kiloux.restopos.ui.RetroButton btnClear;
    private com.kiloux.restopos.ui.RetroButton btnCheckout;
    // End of variables declaration

    private MainFrame mainFrame;
    private CartService cartService;
    private DeviceOrientation orientation;
    private DefaultTableModel tableModel;

    public CartPanel(MainFrame frame, DeviceOrientation orientation) {
        this.mainFrame = frame;
        this.cartService = CartService.getInstance();
        this.orientation = orientation;
        
        initComponents();
        
        initCustom();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        footerPanel = new javax.swing.JPanel();
        funcPanel = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnBack = new com.kiloux.restopos.ui.RetroButton("<< Back");
        btnClear = new com.kiloux.restopos.ui.RetroButton("Clear", UIConfig.DANGER_COLOR, null);
        btnCheckout = new com.kiloux.restopos.ui.RetroButton("CHECKOUT >>");

        setLayout(new java.awt.BorderLayout(10, 10));

        setBackground(UIConfig.BACKGROUND_COLOR);
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        titleLabel.setFont(UIConfig.FONT_HEADER);
        titleLabel.setForeground(UIConfig.TEXT_PRIMARY);
        titleLabel.setText("SHOPPING CART");
        add(titleLabel, java.awt.BorderLayout.NORTH);

        scrollPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        cartTable.setBackground(new java.awt.Color(40, 44, 52));
        cartTable.setFont(UIConfig.FONT_BODY);
        cartTable.setForeground(java.awt.Color.WHITE);
        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Count", "Item Name", "Price", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartTable.setGridColor(new java.awt.Color(80, 80, 80));
        cartTable.setRowHeight(24);
        cartTable.setSelectionBackground(UIConfig.PRIMARY_COLOR);
        cartTable.setSelectionForeground(java.awt.Color.WHITE);
        cartTable.setShowGrid(true);
        cartTable.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(cartTable);

        add(scrollPane, java.awt.BorderLayout.CENTER);

        footerPanel.setOpaque(false);
        footerPanel.setLayout(new java.awt.BorderLayout(10, 10));

        funcPanel.setOpaque(false);
        funcPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        totalLabel.setFont(UIConfig.FONT_TITLE);
        totalLabel.setForeground(UIConfig.TEXT_PRIMARY);
        totalLabel.setText("Total: Rp 0");
        funcPanel.add(totalLabel);

        footerPanel.add(funcPanel, java.awt.BorderLayout.NORTH);

        buttonPanel.setOpaque(false);
        buttonPanel.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        buttonPanel.add(btnBack);

        btnClear.setForeground(new java.awt.Color(200, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        buttonPanel.add(btnClear);

        btnCheckout.setText("CHECKOUT >>");
        btnCheckout.setFont(new java.awt.Font("Arial", 1, 14));
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCheckout);

        footerPanel.add(buttonPanel, java.awt.BorderLayout.CENTER);

        add(footerPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>                        

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        mainFrame.showCard("MENU");
    }                                       

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        cartService.clearCart();
        refreshCart();
    }                                        

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if (cartService.getItems().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cart is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        mainFrame.showCard("CHECKOUT");
    }                                           

    private void initCustom() {
        scrollPane.getViewport().setBackground(new Color(30, 30, 35)); 
        cartTable.getTableHeader().setBackground(new Color(20, 25, 30));
        cartTable.getTableHeader().setForeground(Color.WHITE);
        
        this.tableModel = (DefaultTableModel) cartTable.getModel();
        
        cartService.addListener(() -> refreshCart());
        refreshCart();
    }
    
    public void applyOrientation(DeviceOrientation newOrientation) {
        this.orientation = newOrientation;
    }
    
    public void refreshCart() {
        if (tableModel == null) return;
        tableModel.setRowCount(0);
        List<CartItem> items = cartService.getItems();
        for (CartItem item : items) {
            double sub = item.getMenuItem().getPrice() * item.getQuantity();
            tableModel.addRow(new Object[]{
                item.getQuantity(),
                item.getMenuItem().getName(),
                String.format("%.0f", item.getMenuItem().getPrice()),
                String.format("%.0f", sub)
            });
        }
        
        double subtotal = cartService.getSubtotal();
        double tax = cartService.getTax();
        double total = cartService.getTotal();
        totalLabel.setText(String.format("Subtotal: Rp %.0f | PPN 11%%: Rp %.0f | Total: Rp %.0f", subtotal, tax, total));
    }
}
