package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.dao.OrderDAO;
import com.kiloux.restopos.model.CartItem;
import com.kiloux.restopos.model.Order;
import com.kiloux.restopos.service.CartService;
import com.kiloux.restopos.ui.RetroButton;
import java.awt.*;
import java.awt.event.*;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import javax.swing.*;
import javax.swing.border.BevelBorder;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public class CheckoutPanel extends JPanel {
    
    // Variables declaration - do not modify
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JPanel custForm;
    private javax.swing.JLabel lblCustName;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JPanel advancedBox;
    private com.kiloux.restopos.ui.RetroButton btnSplitBill;
    private com.kiloux.restopos.ui.RetroButton btnVoucher;
    private com.kiloux.restopos.ui.RetroButton btnMember;
    private com.kiloux.restopos.ui.RetroButton btnNote;
    private javax.swing.JTabbedPane paymentTabs;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JLabel lblTotalDue;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel lblCashPaid;
    private javax.swing.JTextField cashPaidField;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JPanel nonCashPanel;
    private javax.swing.JLabel lblMethod;
    private javax.swing.JComboBox<String> methodBox;
    private javax.swing.JLabel lblRef;
    private javax.swing.JTextField refNumberField;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JPanel optsPanel;
    private javax.swing.JRadioButton p58mm;
    private javax.swing.JRadioButton p80mm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane scrollReceipt;
    private javax.swing.JTextArea receiptArea;
    private javax.swing.JPanel actionPanel;
    private com.kiloux.restopos.ui.RetroButton btnCancel;
    private com.kiloux.restopos.ui.RetroButton btnConfirm;
    // End of variables declaration

    private MainFrame mainFrame;
    private CartService cartService;
    private OrderDAO orderDAO;
    private DecimalFormat df = new DecimalFormat("#,###");

    public CheckoutPanel(MainFrame frame) {
        this.mainFrame = frame;
        this.cartService = CartService.getInstance();
        this.orderDAO = new OrderDAO();
        
        initComponents();
        
        initCustom();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        inputPanel = new javax.swing.JPanel();
        custForm = new javax.swing.JPanel();
        lblCustName = new javax.swing.JLabel();
        customerNameField = new javax.swing.JTextField();
        lblOrderType = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        advancedBox = new javax.swing.JPanel();
        btnSplitBill = new com.kiloux.restopos.ui.RetroButton("Split Bill");
        btnVoucher = new com.kiloux.restopos.ui.RetroButton("Apply Voucher");
        btnMember = new com.kiloux.restopos.ui.RetroButton("Member Lookup");
        btnNote = new com.kiloux.restopos.ui.RetroButton("Add Note");
        paymentTabs = new javax.swing.JTabbedPane();
        cashPanel = new javax.swing.JPanel();
        lblTotalDue = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        lblCashPaid = new javax.swing.JLabel();
        cashPaidField = new javax.swing.JTextField();
        lblChange = new javax.swing.JLabel();
        changeLabel = new javax.swing.JLabel();
        nonCashPanel = new javax.swing.JPanel();
        lblMethod = new javax.swing.JLabel();
        methodBox = new javax.swing.JComboBox<>();
        lblRef = new javax.swing.JLabel();
        refNumberField = new javax.swing.JTextField();
        previewPanel = new javax.swing.JPanel();
        optsPanel = new javax.swing.JPanel();
        p58mm = new javax.swing.JRadioButton();
        p80mm = new javax.swing.JRadioButton();
        scrollReceipt = new javax.swing.JScrollPane();
        receiptArea = new javax.swing.JTextArea();
        actionPanel = new javax.swing.JPanel();
        btnCancel = new com.kiloux.restopos.ui.RetroButton("Cancel");
        btnConfirm = new com.kiloux.restopos.ui.RetroButton("Confirm Payment");

        setOpaque(false);
        setLayout(new java.awt.BorderLayout(15, 15));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

        headerPanel.setOpaque(false);
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titleLabel.setForeground(java.awt.Color.WHITE);
        titleLabel.setText("Checkout Counter");
        headerPanel.add(titleLabel, java.awt.BorderLayout.WEST);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setOpaque(false);
        contentPanel.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        // Glass Panel imitation
        inputPanel.setBackground(new java.awt.Color(255, 255, 255, 30));
        inputPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255, 100)), 
            javax.swing.BorderFactory.createTitledBorder(null, "Transaction Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), java.awt.Color.WHITE)));
        inputPanel.setLayout(new javax.swing.BoxLayout(inputPanel, javax.swing.BoxLayout.Y_AXIS));

        custForm.setOpaque(false);
        custForm.setLayout(new java.awt.GridLayout(2, 2, 8, 8));

        lblCustName.setForeground(java.awt.Color.WHITE);
        lblCustName.setText("Customer Name:");
        custForm.add(lblCustName);

        customerNameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerNameField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 150)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        custForm.add(customerNameField);

        lblOrderType.setForeground(java.awt.Color.WHITE);
        lblOrderType.setText("Order Type:");
        custForm.add(lblOrderType);

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dine In", "Take Away", "Delivery" }));
        custForm.add(typeBox);

        inputPanel.add(custForm);

        inputPanel.add(javax.swing.Box.createVerticalStrut(15)); // Spacer

        advancedBox.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Advanced Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), java.awt.Color.WHITE));
        advancedBox.setOpaque(false);
        advancedBox.setLayout(new java.awt.GridLayout(2, 2, 8, 8));

        btnSplitBill.setText("Split Bill");
        btnSplitBill.addActionListener(e -> JOptionPane.showMessageDialog(this, "Split Bill Feature (Mock)"));
        advancedBox.add(btnSplitBill);

        btnVoucher.setText("Apply Voucher");
        btnVoucher.addActionListener(e -> JOptionPane.showMessageDialog(this, "Voucher Applied: DISC10 (Mock)"));
        advancedBox.add(btnVoucher);

        btnMember.setText("Member Lookup");
        btnMember.addActionListener(e -> JOptionPane.showMessageDialog(this, "Member Found: Gold Tier (Mock)"));
        advancedBox.add(btnMember);

        btnNote.setText("Add Note");
        btnNote.addActionListener(e -> JOptionPane.showMessageDialog(this, "Kitchen Note Added."));
        advancedBox.add(btnNote);

        inputPanel.add(advancedBox);
        
        inputPanel.add(javax.swing.Box.createVerticalStrut(15)); // Spacer

        paymentTabs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        cashPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        cashPanel.setOpaque(false);
        cashPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        lblTotalDue.setForeground(java.awt.Color.WHITE);
        lblTotalDue.setText("Total Due:");
        cashPanel.add(lblTotalDue);

        totalLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        totalLabel.setForeground(java.awt.Color.WHITE);
        totalLabel.setText("Rp 0");
        cashPanel.add(totalLabel);

        lblCashPaid.setForeground(java.awt.Color.WHITE);
        lblCashPaid.setText("Cash Received:");
        cashPanel.add(lblCashPaid);

        cashPaidField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cashPaidField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 150)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        cashPanel.add(cashPaidField);

        lblChange.setForeground(java.awt.Color.WHITE);
        lblChange.setText("Change:");
        cashPanel.add(lblChange);

        changeLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        changeLabel.setForeground(UIConfig.PRIMARY_COLOR);
        changeLabel.setText("Rp 0");
        cashPanel.add(changeLabel);

        paymentTabs.addTab("CASH", cashPanel);

        nonCashPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        nonCashPanel.setOpaque(false);
        nonCashPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        lblMethod.setForeground(java.awt.Color.WHITE);
        lblMethod.setText("Method:");
        nonCashPanel.add(lblMethod);

        methodBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QRIS", "Debit BCA", "Credit Card" }));
        nonCashPanel.add(methodBox);

        lblRef.setForeground(java.awt.Color.WHITE);
        lblRef.setText("Ref Number:");
        nonCashPanel.add(lblRef);

        refNumberField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refNumberField.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(100, 100, 150)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        nonCashPanel.add(refNumberField);

        paymentTabs.addTab("NON-CASH", nonCashPanel);

        inputPanel.add(paymentTabs);

        contentPanel.add(inputPanel);

        previewPanel.setBackground(new java.awt.Color(255, 255, 255, 30));
        previewPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255, 100)), 
            javax.swing.BorderFactory.createTitledBorder(null, "Live Receipt Preview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), java.awt.Color.WHITE)));
        previewPanel.setLayout(new java.awt.BorderLayout());

        optsPanel.setOpaque(false);
        optsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        buttonGroup1.add(p58mm);
        p58mm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        p58mm.setForeground(java.awt.Color.WHITE);
        p58mm.setSelected(true);
        p58mm.setText("58mm");
        p58mm.setOpaque(false);
        optsPanel.add(p58mm);

        buttonGroup1.add(p80mm);
        p80mm.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        p80mm.setForeground(java.awt.Color.WHITE);
        p80mm.setText("80mm");
        p80mm.setOpaque(false);
        optsPanel.add(p80mm);

        previewPanel.add(optsPanel, java.awt.BorderLayout.NORTH);

        receiptArea.setEditable(false);
        receiptArea.setBackground(new java.awt.Color(245, 245, 240)); // Paper color
        receiptArea.setColumns(20);
        receiptArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        receiptArea.setForeground(java.awt.Color.BLACK);
        receiptArea.setRows(5);
        receiptArea.setMargin(new java.awt.Insets(10, 10, 10, 10));
        scrollReceipt.setViewportView(receiptArea);

        previewPanel.add(scrollReceipt, java.awt.BorderLayout.CENTER);

        actionPanel.setOpaque(false);
        actionPanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        btnCancel.setText("Cancel");
        // addAction handled in initCustom or here
        actionPanel.add(btnCancel);

        btnConfirm.setText("CONFIRM PAYMENT");
        btnConfirm.setBackground(UIConfig.SUCCESS_COLOR);
        btnConfirm.setForeground(java.awt.Color.WHITE);
        actionPanel.add(btnConfirm);

        previewPanel.add(actionPanel, java.awt.BorderLayout.SOUTH);

        contentPanel.add(previewPanel);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void initCustom() {
        // Logic listeners
        btnCancel.addActionListener(e -> mainFrame.showCard("CART"));
        
        cashPaidField.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) { updateChange(); }
            public void removeUpdate(DocumentEvent e) { updateChange(); }
            public void changedUpdate(DocumentEvent e) { updateChange(); }
        });
        
        btnConfirm.addActionListener(e -> processOrder(typeBox.getSelectedItem().toString()));
        
        // Add Ancestor Listener to refresh when shown
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent event) { 
                generateReceiptPreview(); 
                totalLabel.setText("Rp " + df.format(cartService.getTotal()));
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent event) {}
            public void ancestorMoved(javax.swing.event.AncestorEvent event) {}
        });

        // Initial generation
        generateReceiptPreview();
        totalLabel.setText("Rp " + df.format(cartService.getTotal()));
    }

    private void updateChange() {
        try {
            double total = cartService.getTotal();
            double paid = Double.parseDouble(cashPaidField.getText());
            double change = paid - total;
            changeLabel.setText("Rp " + df.format(change));
            if (change < 0) changeLabel.setForeground(Color.RED);
            else changeLabel.setForeground(Color.GREEN);
        } catch (NumberFormatException e) {
            changeLabel.setText("Rp -");
        }
    }
    

    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(new Color(0, 0, 0, 100));
        g2.fillRect(0, 0, getWidth(), getHeight());
    }
    
    private void generateReceiptPreview() {
        boolean is80 = p80mm.isSelected();
        int width = is80 ? 46 : 30; // Approx char width for 80mm vs 58mm monospace
        
        StringBuilder sb = new StringBuilder();
        String line = "-".repeat(width);
        
        centerText(sb, "KOU RESTAURANT", width);
        centerText(sb, "Jl. Restaurant POS No. 1", width);
        sb.append(line).append("\n");
        
        String dt = java.time.format.DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm").format(LocalDateTime.now());
        sb.append("Date: ").append(dt).append("\n");
        sb.append("Cust: ").append(customerNameField.getText().isEmpty() ? "Guest" : customerNameField.getText()).append("\n");
        sb.append(line).append("\n");
        
        for (CartItem item : cartService.getItems()) {
            String name = item.getMenuItem().getName();
            int qty = item.getQuantity();
            double sub = item.getMenuItem().getPrice() * qty;
            
            if (name.length() > width - 10) name = name.substring(0, width - 10);
            
            // Format: Name on one line, Qty x Price on next? Or simple table?
            // Simple: Name .... Price
            sb.append(name).append("\n");
            String qtyPrice = qty + " x " + df.format(item.getMenuItem().getPrice());
            String totalStr = df.format(sub);
            
            // Align right
            sb.append(String.format(" %-15s %" + (width - 17) + "s\n", qtyPrice, totalStr));
        }
        
        sb.append(line).append("\n");
        String sub = df.format(cartService.getSubtotal());
        String tax = df.format(cartService.getTax());
        String tot = df.format(cartService.getTotal());
        
        sb.append(padRight("Subtotal", width/2)).append(padLeft(sub, width - width/2)).append("\n");
        sb.append(padRight("PPN (11%)", width/2)).append(padLeft(tax, width - width/2)).append("\n");
        sb.append(padRight("TOTAL", width/2)).append(padLeft(tot, width - width/2)).append("\n");
        sb.append(line).append("\n");
        
        centerText(sb, "THANK YOU!", width);
        
        receiptArea.setText(sb.toString());
    }
    
    private void centerText(StringBuilder sb, String text, int width) {
        int pad = (width - text.length()) / 2;
        if (pad > 0) sb.append(" ".repeat(pad));
        sb.append(text).append("\n");
    }
    
    private String padRight(String s, int n) {
        return String.format("%-" + n + "s", s);
    }
    
    private String padLeft(String s, int n) {
        return String.format("%" + n + "s", s);
    }
    
    private void processOrder(String orderType) {
        if (cartService.getItems().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Cart is empty!");
            return;
        }
        
        String method = "CASH";
        if (paymentTabs.getSelectedIndex() == 1) {
             method = "NON_CASH"; // Or specific value from combo
        } else {
             // Validate Cash
             try {
                 double v = Double.parseDouble(cashPaidField.getText());
                 if (v < cartService.getTotal()) {
                     com.kiloux.restopos.utils.SoundManager.getInstance().play("error");
                     JOptionPane.showMessageDialog(this, "Insufficient Cash!", "Error", JOptionPane.WARNING_MESSAGE);
                     return;
                 }
             } catch(Exception e) {
                 com.kiloux.restopos.utils.SoundManager.getInstance().play("error");
                 JOptionPane.showMessageDialog(this, "Invalid Cash Amount", "Error", JOptionPane.WARNING_MESSAGE);
                 return;
             }
        }
        
        Order ord = new Order();
        ord.setTableId(cartService.getSelectedTableId() == -1 ? 0 : cartService.getSelectedTableId());
        ord.setOrderType(orderType);
        ord.setStatus("PENDING");
        ord.setCustomerName(customerNameField.getText());
        ord.setTotalAmount(cartService.getTotal());
        ord.setPaymentStatus("PAID");
        
        if (orderDAO.createOrder(ord, cartService.getItems()) != -1) {
            com.kiloux.restopos.utils.SoundManager.getInstance().play("success");
            JOptionPane.showMessageDialog(this, "Transaction Successful!\nPrinting Receipt...", "Success", JOptionPane.INFORMATION_MESSAGE);
            cartService.clearCart();
            mainFrame.showCard("ONBOARDING"); 
        } else {
            com.kiloux.restopos.utils.SoundManager.getInstance().play("error");
            JOptionPane.showMessageDialog(this, "Transaction Failed Db Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
