package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.dao.OrderDAO;
import com.kiloux.restopos.model.Order;
import com.kiloux.restopos.utils.DatabaseManager;
import java.awt.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.BevelBorder;

public class CustomerMonitorPanel extends JPanel {

    private MainFrame mainFrame;
    private OrderDAO orderDAO;
    private Timer refreshTimer;
    
    // Variables declaration - do not modify
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel lblPrep;
    private javax.swing.JPanel preparingPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel lblReady;
    private javax.swing.JPanel readyPanel;
    // End of variables declaration

    public CustomerMonitorPanel(MainFrame frame) {
        this.mainFrame = frame;
        this.orderDAO = new OrderDAO();
        initComponents();
        
        initCustom();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        hintLabel = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        lblPrep = new javax.swing.JLabel();
        preparingPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        lblReady = new javax.swing.JLabel();
        readyPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(java.awt.Color.BLACK);

        headerPanel.setBackground(new java.awt.Color(0, 0, 128));
        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        titleLabel.setForeground(java.awt.Color.WHITE);
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("ORDER STATUS MONITOR");
        headerPanel.add(titleLabel, java.awt.BorderLayout.CENTER);

        hintLabel.setForeground(java.awt.Color.LIGHT_GRAY);
        hintLabel.setText("[ESC] Back");
        headerPanel.add(hintLabel, java.awt.BorderLayout.EAST);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        contentPanel.setBackground(java.awt.Color.BLACK);
        contentPanel.setLayout(new java.awt.GridLayout(1, 2, 5, 0));

        leftPanel.setBackground(java.awt.Color.BLACK);
        leftPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 2, java.awt.Color.DARK_GRAY));
        leftPanel.setLayout(new java.awt.BorderLayout());

        lblPrep.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblPrep.setForeground(java.awt.Color.YELLOW);
        lblPrep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrep.setText("PREPARING");
        lblPrep.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 0));
        leftPanel.add(lblPrep, java.awt.BorderLayout.NORTH);

        preparingPanel.setBackground(java.awt.Color.BLACK);
        preparingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        leftPanel.add(preparingPanel, java.awt.BorderLayout.CENTER);

        contentPanel.add(leftPanel);

        rightPanel.setBackground(java.awt.Color.BLACK);
        rightPanel.setLayout(new java.awt.BorderLayout());

        lblReady.setFont(new java.awt.Font("Arial", 1, 28)); // NOI18N
        lblReady.setForeground(java.awt.Color.GREEN);
        lblReady.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReady.setText("READY TO SERVE");
        lblReady.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 20, 0));
        rightPanel.add(lblReady, java.awt.BorderLayout.NORTH);

        readyPanel.setBackground(java.awt.Color.BLACK);
        readyPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));
        rightPanel.add(readyPanel, java.awt.BorderLayout.CENTER);

        contentPanel.add(rightPanel);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void initCustom() {
        // Auto Refresh
        refreshTimer = new Timer(5000, e -> fetchData());
        refreshTimer.start();
        
        // Key Binding for Exit
        getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke("ESCAPE"), "back");
        getActionMap().put("back", new AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                mainFrame.showCard("ONBOARDING"); 
            }
        });
    }

    // We need ad-hoc queries because OrderDAO might not have specific separation methods yet
    private void fetchData() {
        preparingPanel.removeAll();
        readyPanel.removeAll();
        
        // Fetch Logic
        // PREPARING: Status = PENDING, COOKING
        // READY: Status = COMPLETED (limit to last 10?)
        
        List<String> preparing = getQueueNumbers("PENDING", "COOKING");
        List<String> ready = getQueueNumbers("COMPLETED"); // We assume COMPLETED is "Ready"
        
        for (String q : preparing) {
            JLabel badge = createBadge(q, Color.YELLOW);
            preparingPanel.add(badge);
        }
        
        for (String q : ready) {
            JLabel badge = createBadge(q, Color.GREEN);
            readyPanel.add(badge);
        }
        
        preparingPanel.revalidate(); preparingPanel.repaint();
        readyPanel.revalidate(); readyPanel.repaint();
    }
    
    private List<String> getQueueNumbers(String... statuses) {
        List<String> list = new ArrayList<>();
        StringBuilder q = new StringBuilder("SELECT queue_number FROM orders WHERE status IN (");
        for(int i=0; i<statuses.length; i++) {
            q.append("'").append(statuses[i]).append("'");
            if(i < statuses.length-1) q.append(",");
        }
        q.append(") AND date(created_at) = CURDATE() ORDER BY id DESC LIMIT 12");
        
        try (Connection conn = DatabaseManager.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(q.toString())) {
             while(rs.next()) {
                 list.add(String.format("%03d", rs.getInt(1)));
             }
        } catch(Exception e) { e.printStackTrace(); }
        return list;
    }
    
    private JLabel createBadge(String num, Color c) {
        JLabel l = new JLabel(num);
        l.setFont(new Font("Monospaced", Font.BOLD, 48));
        l.setForeground(c);
        l.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(c, 2),
            BorderFactory.createEmptyBorder(5, 15, 5, 15)
        ));
        return l;
    }
}

