package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.dao.OrderDAO;
import com.kiloux.restopos.model.CartItem;
import com.kiloux.restopos.model.Order;
import com.kiloux.restopos.ui.RetroButton;
import java.awt.*;
import java.util.List;
import javax.swing.*;
import javax.swing.border.BevelBorder;

public class KitchenPanel extends JPanel {
    
    // Variables declaration - do not modify
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel titleLabel;
    private com.kiloux.restopos.ui.RetroButton refreshButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel ticketContainer;
    // End of variables declaration

    private OrderDAO orderDAO;
    private Timer refreshTimer;

    public KitchenPanel(MainFrame frame) {
        this.orderDAO = new OrderDAO();
        
        initComponents();
        
        initCustomLogic();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        refreshButton = new com.kiloux.restopos.ui.RetroButton("REFRESH");
        scrollPane = new javax.swing.JScrollPane();
        ticketContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBackground(java.awt.Color.BLACK); // Retro CRT Black

        headerPanel.setBackground(java.awt.Color.DARK_GRAY);
        headerPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(new java.awt.Font("Monospaced", 1, 20)); // NOI18N
        titleLabel.setForeground(java.awt.Color.GREEN);
        titleLabel.setText(" KITCHEN DISPLAY SYSTEM (KDS) - LIVE");
        headerPanel.add(titleLabel, java.awt.BorderLayout.WEST);

        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshOrders();
            }
        });
        headerPanel.add(refreshButton, java.awt.BorderLayout.EAST);

        add(headerPanel, java.awt.BorderLayout.NORTH);

        scrollPane.setBorder(null);

        ticketContainer.setBackground(java.awt.Color.BLACK);
        ticketContainer.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15));
        scrollPane.setViewportView(ticketContainer);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void initCustomLogic() {
        // Customizations not handled by Designer
        scrollPane.getViewport().setBackground(Color.BLACK);
        
        // Auto Refresh
        refreshTimer = new Timer(5000, e -> refreshOrders());
        refreshTimer.start();
        refreshOrders(); 
    }
    
    private void refreshOrders() {
        ticketContainer.removeAll();
        List<Order> orders = orderDAO.getPendingOrders();
        
        if (orders.isEmpty()) {
            JLabel empty = new JLabel("NO ACTIVE ORDERS");
            empty.setForeground(Color.GREEN.darker());
            empty.setFont(new Font("Monospaced", Font.BOLD, 24));
            ticketContainer.add(empty);
        } else {
            for (Order o : orders) {
                ticketContainer.add(createTicket(o));
            }
        }
        ticketContainer.revalidate();
        ticketContainer.repaint();
    }
    
    private JPanel createTicket(Order order) {
        JPanel card = new JPanel(new BorderLayout());
        card.setPreferredSize(new Dimension(250, 350));
        card.setBackground(Color.BLACK);
        card.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));
        
        // Header
        JPanel head = new JPanel(new BorderLayout());
        head.setBackground(Color.GREEN);
        JLabel qLbl = new JLabel(" #" + order.getQueueNumber());
        qLbl.setFont(new Font("Arial", Font.BOLD, 24));
        qLbl.setForeground(Color.BLACK);
        
        JLabel timeLbl = new JLabel(order.getOrderType() + " ");
        timeLbl.setFont(new Font("Arial", Font.BOLD, 12));
        timeLbl.setForeground(Color.BLACK);
        
        head.add(qLbl, BorderLayout.WEST);
        head.add(timeLbl, BorderLayout.EAST);
        card.add(head, BorderLayout.NORTH);
        
        // Body (Items)
        JPanel body = new JPanel();
        body.setLayout(new BoxLayout(body, BoxLayout.Y_AXIS));
        body.setBackground(Color.BLACK);
        body.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        
        JLabel cust = new JLabel("Customer: " + (order.getCustomerName() == null ? "-" : order.getCustomerName()));
        cust.setForeground(Color.WHITE);
        cust.setFont(new Font("Monospaced", Font.PLAIN, 12));
        body.add(cust);
        body.add(new JSeparator());
        
        if (order.getItems() != null) {
            for (CartItem item : order.getItems()) {
                JLabel l = new JLabel(item.getQuantity() + "x " + item.getMenuItem().getName().toUpperCase());
                l.setForeground(Color.GREEN);
                l.setFont(new Font("Monospaced", Font.BOLD, 14));
                body.add(l);
                
                if (item.getNotes() != null && !item.getNotes().isEmpty()) {
                    JLabel n = new JLabel("  *" + item.getNotes());
                    n.setForeground(Color.YELLOW);
                    n.setFont(new Font("Monospaced", Font.ITALIC, 12));
                    body.add(n);
                }
                body.add(Box.createVerticalStrut(5));
            }
        }
        card.add(body, BorderLayout.CENTER);
        
        // Footer (Done)
        RetroButton doneBtn = new RetroButton("DONE");
        doneBtn.setBackground(Color.DARK_GRAY);
        doneBtn.setForeground(Color.WHITE);
        doneBtn.addActionListener(e -> {
            orderDAO.updateStatus(order.getId(), "COMPLETED");
            refreshOrders();
        });
        card.add(doneBtn, BorderLayout.SOUTH);
        
        return card;
    }
}

