package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.service.UserService;
import com.kiloux.restopos.ui.RetroButton;
import java.awt.*;
import javax.swing.*;

/**
 * NetBeans-friendly LoginPanel.
 */
public class LoginPanel extends JPanel {
    
    private MainFrame mainFrame;
    
    // Variables declaration - do not modify
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JPanel buttonPanel;
    private com.kiloux.restopos.ui.RetroButton btnLogin;
    private com.kiloux.restopos.ui.RetroButton btnRegister;
    // End of variables declaration

    public LoginPanel(MainFrame frame) {
        this.mainFrame = frame;
        initComponents();
        setOpaque(false); // Let Desktop gradient show through
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainContainer = new com.kiloux.restopos.ui.AeroPanel(new BorderLayout(15, 15));
        titleLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        buttonPanel = new javax.swing.JPanel();
        btnRegister = new com.kiloux.restopos.ui.RetroButton("Register");
        btnLogin = new com.kiloux.restopos.ui.RetroButton("Sign In");

        setLayout(new java.awt.GridBagLayout());

        mainContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainContainer.setPreferredSize(new java.awt.Dimension(380, 240));
        mainContainer.setLayout(new java.awt.BorderLayout(15, 15));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(30, 50, 80));
        titleLabel.setText("User Login");
        mainContainer.add(titleLabel, java.awt.BorderLayout.NORTH);

        formPanel.setOpaque(false);
        formPanel.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        userLabel.setText("Username:");
        formPanel.add(userLabel);

        userField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formPanel.add(userField);

        passLabel.setText("Password:");
        formPanel.add(passLabel);

        passField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formPanel.add(passField);

        mainContainer.add(formPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setOpaque(false);
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnRegister.setPreferredSize(new java.awt.Dimension(80, 30));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        buttonPanel.add(btnRegister);

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogin.setPreferredSize(new java.awt.Dimension(100, 30));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        buttonPanel.add(btnLogin);

        mainContainer.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        add(mainContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>                        

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        performLogin();
    }                                        

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {                                            
        mainFrame.showCard("REGISTER");
    }                                           
    
    // ... performLogin logic
    private void performLogin() {
        String u = userField.getText();
        String p = new String(passField.getPassword());
        
        UserService userService = UserService.getInstance();
        if (userService.login(u, p)) {
            String role = userService.getCurrentRole();
            if ("CLIENT".equalsIgnoreCase(role)) {
                mainFrame.showCard("MONITOR");
            } else if ("ADMIN".equalsIgnoreCase(role)) {
                mainFrame.showCard("ADMIN");
            } else {
                // Cashier or Staff
                mainFrame.showCard("ONBOARDING");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

