package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.DeviceOrientation;
import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.dao.MenuItemDAO;
import com.kiloux.restopos.gui.dialog.ItemDetailDialog;
import com.kiloux.restopos.model.MenuItem;
import com.kiloux.restopos.ui.RetroMenuItem;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.List;
import javax.swing.*;

public class MenuPanel extends JPanel {
    
    // Variables declaration - do not modify
    private javax.swing.JPanel topContainer;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel filterPanel;
    private javax.swing.JPanel searchBox;
    private javax.swing.JTextField searchField;
    private javax.swing.JPanel chipsPanel;
    // Chips button placeholders can be declared here if static, or added dynamically
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel gridContainer;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel paginationPanel;
    private javax.swing.JButton btnPrev;
    private javax.swing.JLabel lblPage;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnCart;
    // End of variables declaration

    private MainFrame mainFrame;
    private MenuItemDAO menuDAO;
    private DeviceOrientation orientation;
    
    // Pagination
    private List<MenuItem> allItems;
    private int currentPage = 0;
    private static final int ITEMS_PER_PAGE = 8;

    public MenuPanel(MainFrame frame, DeviceOrientation orientation) {
        this.mainFrame = frame;
        this.menuDAO = new MenuItemDAO();
        this.orientation = orientation;
        this.allItems = menuDAO.getAllMenuItems();
        
        initComponents();
        
        initCustom();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        topContainer = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        filterPanel = new javax.swing.JPanel();
        searchBox = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        chipsPanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        gridContainer = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        paginationPanel = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        setBackground(UIConfig.BACKGROUND_COLOR);

        topContainer.setBackground(UIConfig.BACKGROUND_COLOR);
        topContainer.setOpaque(true);
        topContainer.setLayout(new java.awt.BorderLayout());

        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        headerPanel.setOpaque(false);
        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setFont(UIConfig.FONT_HEADER);
        titleLabel.setForeground(UIConfig.TEXT_PRIMARY);
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("MENU KAMI");
        headerPanel.add(titleLabel, java.awt.BorderLayout.CENTER);

        topContainer.add(headerPanel, java.awt.BorderLayout.NORTH);

        filterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 10, 15));
        filterPanel.setOpaque(false);
        filterPanel.setLayout(new javax.swing.BoxLayout(filterPanel, javax.swing.BoxLayout.Y_AXIS));

        searchBox.setBackground(java.awt.Color.WHITE);
        searchBox.setBorder(javax.swing.BorderFactory.createLineBorder(UIConfig.BORDER_COLOR));
        searchBox.setPreferredSize(new java.awt.Dimension(200, 30));
        searchBox.setLayout(new java.awt.BorderLayout());

        searchField.setFont(UIConfig.FONT_BODY);
        searchField.setText("CARI MENU...");
        searchField.setBorder(null);
        searchBox.add(searchField, java.awt.BorderLayout.CENTER);

        filterPanel.add(searchBox);
        
        // Add vertical strut imitation
        javax.swing.Box.Filler strut = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        filterPanel.add(strut);

        chipsPanel.setOpaque(false);
        chipsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        filterPanel.add(chipsPanel);

        topContainer.add(filterPanel, java.awt.BorderLayout.CENTER);

        add(topContainer, java.awt.BorderLayout.NORTH);

        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        gridContainer.setBackground(UIConfig.BACKGROUND_COLOR);
        gridContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridContainer.setLayout(new java.awt.GridLayout(0, 4, 10, 10));
        scrollPane.setViewportView(gridContainer);

        add(scrollPane, java.awt.BorderLayout.CENTER);

        footerPanel.setBackground(UIConfig.BACKGROUND_COLOR);
        footerPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, UIConfig.BORDER_COLOR));
        footerPanel.setOpaque(true);
        footerPanel.setLayout(new java.awt.BorderLayout());

        paginationPanel.setOpaque(false);
        paginationPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        btnPrev.setText("<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        paginationPanel.add(btnPrev);

        lblPage.setFont(UIConfig.FONT_RETRO_DIGITAL);
        lblPage.setText("PAGE 1");
        paginationPanel.add(lblPage);

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        paginationPanel.add(btnNext);

        footerPanel.add(paginationPanel, java.awt.BorderLayout.WEST);

        btnCart.setBackground(UIConfig.PRIMARY_COLOR);
        btnCart.setFont(UIConfig.FONT_BODY);
        btnCart.setForeground(java.awt.Color.WHITE);
        btnCart.setText("CART [0] - Rp 0");
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        footerPanel.add(btnCart, java.awt.BorderLayout.EAST);

        add(footerPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>                        

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {                                        
        if (currentPage > 0) {
            currentPage--;
            applyGridLayout();
        }
    }                                       

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int maxPage = (int) Math.ceil((double)allItems.size() / ITEMS_PER_PAGE) - 1;
        if (currentPage < maxPage) {
            currentPage++;
            applyGridLayout();
        }
    }                                       

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {                                        
        mainFrame.showCard("CART");
    }                                       

    private void initCustom() {
        // Initialization of things that NetBeans Editor can't handle perfectly or dynamic content
        scrollPane.getViewport().setBackground(UIConfig.BACKGROUND_COLOR);
        
        // Chips (Retro Buttons)
        String[] categories = {"ALL", "CHICKEN", "RAMEN", "BEVS"};
        for (String cat : categories) {
            JButton chip = new JButton(cat);
            chip.setFont(UIConfig.FONT_SMALL);
            chip.setBackground(UIConfig.SECONDARY_COLOR);
            chip.setForeground(UIConfig.TEXT_PRIMARY);
            chip.setFocusPainted(false);
            chipsPanel.add(chip);
        }
        
        // Real-time Update
        com.kiloux.restopos.service.CartService.getInstance().addListener(() -> {
            int count = com.kiloux.restopos.service.CartService.getInstance().getItems().stream().mapToInt(com.kiloux.restopos.model.CartItem::getQuantity).sum();
            double total = com.kiloux.restopos.service.CartService.getInstance().getTotal();
            btnCart.setText(String.format("CART [%d] - Rp %,.0f", count, total));
        });
        
        applyGridLayout();
        updatePaginationState();
    }

    private void applyGridLayout() {
        gridContainer.removeAll();
        // 4 Columns Fixed (As per user request)
        // gridContainer layout is already set in initComponents
        
        // Pagination Logic
        int start = currentPage * ITEMS_PER_PAGE;
        int end = Math.min(start + ITEMS_PER_PAGE, allItems.size());
        
        List<MenuItem> pageItems = allItems.subList(start, end);
        int index = start + 1;
        
        for (MenuItem item : pageItems) {
            final int currIndex = index++;
            RetroMenuItem card = new RetroMenuItem(
                currIndex, 
                item.getName().toUpperCase(), 
                String.format("Rp %.0f", item.getPrice()), 
                loadImageFor(item),
                () -> new ItemDetailDialog(mainFrame, item).setVisible(true)
            );
            gridContainer.add(card);
        }
        
        // Fill empty slots to maintain grid structure (optional, but looks better in retro grid)
        int remainder = ITEMS_PER_PAGE - pageItems.size();
        for(int i=0; i<remainder; i++) {
             JPanel placeholder = new JPanel();
             placeholder.setOpaque(false);
             gridContainer.add(placeholder);
        }
        
        updatePaginationState();
        gridContainer.revalidate();
        gridContainer.repaint();
    }
    
    private Image loadImageFor(MenuItem item) {
       try {
            String path = "/images/" + (item.getImagePath() != null ? item.getImagePath() : "default.jpg");
            java.net.URL imgUrl = getClass().getResource(path);
             if (imgUrl == null) {
                  java.io.File file = new java.io.File("src/main/resources" + path);
                  if (file.exists()) imgUrl = file.toURI().toURL();
             }
            
            if (imgUrl != null) {
                BufferedImage bi = javax.imageio.ImageIO.read(imgUrl);
                if (bi != null) {
                    return bi.getScaledInstance(64, 64, Image.SCALE_SMOOTH);
                }
            } 
        } catch (Exception e) {
            // Null returns default placeholder in RetroMenuItem
        }
        return null; // RetroMenuItem handles null with isometric box
    }
    
    private void updatePaginationState() {
        int maxPage = (int) Math.ceil((double)allItems.size() / ITEMS_PER_PAGE) - 1;
        if (maxPage < 0) maxPage = 0;
        
        lblPage.setText("PAGE " + (currentPage + 1) + " / " + (maxPage + 1));
        btnPrev.setEnabled(currentPage > 0);
        btnNext.setEnabled(currentPage < maxPage);
    }
    
    public void applyOrientation(DeviceOrientation newOrientation) {
        this.orientation = newOrientation;
        // Grid is fixed 4 columns per user spec ("Grid (4 kolom)"), so orientation might just change container size
        revalidate();
    }
}

