package com.kiloux.restopos.gui;

import com.kiloux.restopos.config.UIConfig;
import com.kiloux.restopos.service.UserService;
import com.kiloux.restopos.ui.RetroButton;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.BevelBorder;

public class RegisterPanel extends JPanel {
    
    // Variables declaration - do not modify
    private javax.swing.JPanel windowPanel;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JLabel userLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JPanel buttonPanel;
    private com.kiloux.restopos.ui.RetroButton btnCancel;
    private com.kiloux.restopos.ui.RetroButton btnOk;
    // End of variables declaration

    private MainFrame mainFrame;

    public RegisterPanel(MainFrame frame) {
        this.mainFrame = frame;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        windowPanel = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        confirmLabel = new javax.swing.JLabel();
        confirmField = new javax.swing.JPasswordField();
        buttonPanel = new javax.swing.JPanel();
        btnCancel = new com.kiloux.restopos.ui.RetroButton("Cancel");
        btnOk = new com.kiloux.restopos.ui.RetroButton("Create");

        setLayout(new java.awt.GridBagLayout());

        setBackground(UIConfig.BACKGROUND_COLOR);

        windowPanel.setBackground(UIConfig.WIN98_GREY);
        windowPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        windowPanel.setPreferredSize(new java.awt.Dimension(350, 260));
        windowPanel.setLayout(new java.awt.BorderLayout());

        titleBar.setBackground(UIConfig.WIN98_TITLE_ACTIVE_START);
        titleBar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        titleLabel.setForeground(java.awt.Color.WHITE);
        titleLabel.setText("New User Registration");
        titleBar.add(titleLabel);

        windowPanel.add(titleBar, java.awt.BorderLayout.NORTH);

        formPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        formPanel.setOpaque(false);
        formPanel.setLayout(new java.awt.GridBagLayout());

        userLabel.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(userLabel, gridBagConstraints);

        userField.setColumns(15);
        userField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(userField, gridBagConstraints);

        passLabel.setText("Password:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(passLabel, gridBagConstraints);

        passField.setColumns(15);
        passField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(passField, gridBagConstraints);

        confirmLabel.setText("Confirm Pass:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(confirmLabel, gridBagConstraints);

        confirmField.setColumns(15);
        confirmField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formPanel.add(confirmField, gridBagConstraints);

        windowPanel.add(formPanel, java.awt.BorderLayout.CENTER);

        buttonPanel.setOpaque(false);
        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCancel);

        btnOk.setText("Create");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        buttonPanel.add(btnOk);

        windowPanel.add(buttonPanel, java.awt.BorderLayout.SOUTH);

        add(windowPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>                        

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        mainFrame.showCard("LOGIN");
    }                                         

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {                                      
        register();
    }                                     

    private void register() {
         String u = userField.getText();
         String p = new String(passField.getPassword());
         String c = new String(confirmField.getPassword());
         
         if (!p.equals(c)) {
             JOptionPane.showMessageDialog(this, "Passwords do not match!", "Error", JOptionPane.ERROR_MESSAGE);
             return;
         }
         
         if(UserService.getInstance().register(u, p)) {
             JOptionPane.showMessageDialog(this, "User Created!", "Success", JOptionPane.INFORMATION_MESSAGE);
             mainFrame.showCard("LOGIN");
         } else {
             JOptionPane.showMessageDialog(this, "Registration Failed (User exists?)", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }
}

